### ISSUE TITLE
themedCSS does not work like it used to

### ISSUE THREAD

**Issue by NightJar** [silverstripe/cwp-starter-theme#26]
https://github.com/silverstripe/cwp-starter-theme/blob/148782b3241a671afbfc4eb9179d91c7aada3615/templates/SilverStripe/Blog/Model/Layout/BlogPost.ss#L1

This causes:
`[Emergency] Uncaught InvalidArgumentException: The css file doesn't exist. Please check if the blog.css exists in any context or search for themedCSS references calling this file in your templates.`
(Death).

**Comment by robbieaverill** [comment]
Yep! We need to use the module reference and match https://github.com/silverstripe/silverstripe-blog/blob/master/templates/SilverStripe/Blog/Model/Layout/BlogPost.ss#L1

**Comment by NightJar** [comment]
I thought `themedCSS` was re-introduced in core at `4.0.1` - is it a regression perhaps?
Or, I never saw the outcome of the discussion, was it never re-implemented?

**Comment by robbieaverill** [comment]
If the intention is to override the existing blog file, we should use `<% themedCSS('starter/dist/css/blog.css') %>` for example.

If this should be transparent and bring through the blog module's stylesheet (like the blog template does) then we should use `<% require css('silverstripe/blog: client/dist/styles/main.css') %>`

**Comment by NightJar** [comment]
First example is still not entirely backwards compatible, as it references the theme name still.
I thought the new incarnation of this function was to iterate over the `SilverStripe\View\SSViewer.theme` list and pick the first available.

**Comment by robbieaverill** [comment]
Here are some assumptions:

* This code hasn't changed from the SS3 version
* The file didn't exist in this theme in the SS3 version
* It probably now throws an exception if it can't be found, since requirements must exist in SS4 now
* We should remove it if we're arbitrarily looking for a file that may not exist in any themes, particularly in the theme that is defining the requirement for it, or;
* We should reference the original blog's asset instead

My suggestion would be to remove it - the theme defines its own styles for blog anyway =)

**Comment by robbieaverill** [comment]
PR at #26
